print("累積代入の計算ができます")
num_1=float(input('一つ目の数字を入力してください: '))
num_2=float(input('二つ目の数字を入力してください: '))
print('足し算')
a=num_1
a+=num_2
print(a)
print('引き算')
b=num_1
b-=num_2
print(b)
print('掛け算')
c=num_1
c*=num_2
print(c)
print('割り算(小数点以下あり)')
d=num_1
d/=num_2
print(d)
print('割り算（小数点以下切り捨て）')
e=num_1
e//=num_2
print(e)
print('べき乗（累乗）')
f=num_1
f**=num_2
print(f)
print('余りの計算')
g=num_1
g%=num_2
print(g)
print('入力した二つの数字が等しいか調べる')
equal=(num_1==num_2)
print(equal)
print('入力した二つの数字が等しくないか調べる')
not_equal=(num_1!=num_2)
print(not_equal)
print('一つ目の数字が二つ目の数字より大きいか調べる')
greater_than=(num_1>num_2)
print(greater_than)
print('二つ目の数字が一つ目の数字以上か調べる')
greater_than_or_equal=(num_1<=num_2)
print(greater_than_or_equal)
input('Enterを押すと終了します')